### ISSUE TITLE
View Third Party Libraries

### ISSUE THREAD

**Issue by zzimbler-tagsafe** [swishjam/swishjam#21]
- Create a new tab in the dashboard to visualize the third party libraries found in the data captured by instrumentation
- Display the third parties in a list and display any information we have about them in an orderly way

**Comment by zzimbler** [comment]
@Aashish-Upadhyay-101 yes this project is active. We have not prioritized a public slack channel yet, but I've created one that you can join if you're interested: https://join.slack.com/t/slack-8bu7708/shared_invite/zt-1uyzm82g3-tN98gLm5aQer5G~~PO86ZQ

**Comment by Aashish-Upadhyay-101** [comment]
@zzimbler I want to contribute !! can you open up a bunch of new issues ??
